# https://pre-commit.com/
# pre commit hooks for python
# install with:
# uv sync --only-dev
# pre-commit install
# pre-commit run --all-files

# somehow `noqa` is not working for some reason, thus ignoring globally, should be checked from time to time
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.2
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: ^crypticorn_utils/
        args: [--config-file=mypy.ini]
        additional_dependencies: [pydantic>=2.0.0]
